title: Laffa Neosia
author: Laffa6
email: laffa6@domain.com
description: Web Developper junior 

# social links
twitter_username: @Laffa6
github_username:  https://github.com/Laffa6

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
